name: Maven CI/CD Pipeline

on:
  push:
    branches:
      - develop        # Trigger the workflow on push to the 'develop' branch
  pull_request:
    branches:
      - develop        # Trigger the workflow on pull requests to the 'develop' branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'   # Use the Java version required by your project
          distribution: 'adopt' # Options: adopt, zulu, temurin

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run tests
      - name: Run Tests
        run: mvn test -Dbrowser=firefox

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-test     # Ensure deployment happens only after build-and-test job succeeds

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Add deployment steps
      - name: Example Deployment Step
        run: echo "Deploying application from develop branch"
